name: Deploy

on: [push]

env:
  TZ: 'Asia/Taipei'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Hexo Blog
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Checkout private submodules(themes or something else).

      - name: Timezone set Asia/Taipei
        run: sudo timedatectl set-timezone 'Asia/Taipei'
      
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Install Hexo Theme
        run: |
          git clone https://github.com/XPoet/hexo-theme-keep --depth=1 themes/keep

      - name: Hexo Deploy
        id: deploy
        uses: sma11black/hexo-action@v1.0.3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}

      - name: Get the output
        run: echo "${{ steps.deploy.outputs.notify }}"
